/* Citations de repos — style Total War : citation courte + source.
   Sources antiques et historiques du domaine public. Les attributions
   incertaines ou apocryphes sont marquées « attribué à ». */
window.QUOTES=[
/* — Proverbes et maximes latines — */
{t:"La mère d'un lâche ne pleure pas.",s:"Proverbe latin"},
{t:"La fortune sourit aux audacieux.",s:"Virgile, Énéide"},
{t:"Qui veut la paix prépare la guerre.",s:"Végèce"},
{t:"Un brave peut tomber, il ne peut céder.",s:"Proverbe latin"},
{t:"La victoire aime la prudence.",s:"Proverbe latin"},
{t:"Par des sentiers ardus jusqu'aux étoiles.",s:"Devise latine (Per aspera ad astra)"},
{t:"Le sort en est jeté.",s:"Jules César, au passage du Rubicon"},
{t:"Je suis venu, j'ai vu, j'ai vaincu.",s:"Jules César"},
{t:"Les lois se taisent parmi les armes.",s:"Cicéron"},
{t:"Le nerf de la guerre : l'argent sans limite.",s:"Cicéron"},
{t:"Cueille le jour, sans te fier au lendemain.",s:"Horace"},
{t:"La goutte d'eau creuse la pierre non par force, mais en tombant souvent.",s:"Ovide"},
{t:"Un esprit sain dans un corps sain.",s:"Juvénal"},
{t:"Pas de jour sans une ligne.",s:"Pline l'Ancien, d'après Apelle"},
{t:"Il faut oser : la fortune aide les forts.",s:"Térence"},
{t:"Tant qu'il y a de la vie, il y a de l'espoir.",s:"Cicéron"},
{t:"L'usage est le meilleur des maîtres.",s:"Proverbe latin"},
{t:"La pratique est le meilleur des instructeurs.",s:"Publilius Syrus"},
{t:"Celui qui a vaincu la douleur a vaincu plus qu'un ennemi.",s:"Publilius Syrus"},
{t:"Le gain n'a pas d'odeur, la gloire n'a pas de prix.",s:"D'après Juvénal"},
{t:"On ne doit pas juger de l'arbre par l'écorce.",s:"Proverbe latin"},
{t:"L'occasion a les cheveux sur le front : saisis-la quand elle passe.",s:"D'après Phèdre"},
{t:"Le courage croît en osant, la peur en hésitant.",s:"Publilius Syrus"},
{t:"Double victoire : se vaincre soi-même dans la victoire.",s:"Publilius Syrus"},
{t:"Il est trop tard pour être prudent quand on est au milieu du danger.",s:"Publilius Syrus"},
{t:"La nécessité donne la loi et ne la reçoit pas.",s:"Publilius Syrus"},
{t:"L'homme courageux se fait plus de bien qu'il n'en reçoit.",s:"Publilius Syrus"},
{t:"Chaque jour est une vie nouvelle pour le sage.",s:"Publilius Syrus"},
{t:"Qui peut se vaincre lui-même n'a rien à craindre.",s:"Publilius Syrus"},
{t:"La roche Tarpéienne est proche du Capitole.",s:"Adage romain"},
{t:"Souviens-toi que tu es mortel.",s:"Adage romain, dit au triomphateur"},
{t:"Malheur aux vaincus !",s:"Brennus, chef gaulois, d'après Tite-Live"},
{t:"L'aigle ne chasse pas les mouches.",s:"Adage latin"},
{t:"La renommée donne des ailes.",s:"Adage latin"},
{t:"Apprendre, c'est souffrir.",s:"Adage latin (Discere pati)"},
{t:"Vouloir, c'est pouvoir.",s:"Adage latin"},
{t:"À l'impossible nul n'est tenu.",s:"Adage de droit romain"},
{t:"Rien ne sèche plus vite qu'une larme.",s:"Cicéron, d'après Apollonios"},
{t:"C'est en forgeant qu'on devient forgeron.",s:"Proverbe d'origine latine"},
{t:"Hâte-toi lentement.",s:"Devise d'Auguste, d'après Suétone"},
{t:"L'homme est un loup pour l'homme.",s:"Plaute"},
{t:"Je suis un homme : rien d'humain ne m'est étranger.",s:"Térence"},
{t:"Fais ce que tu fais.",s:"Adage latin (Age quod agis)"},
{t:"Pendant qu'ils vivaient, d'autres discutaient.",s:"Adage latin"},
{t:"Le monde appartient à ceux qui se lèvent tôt.",s:"Proverbe d'origine latine"},
{t:"Aide-toi, le ciel t'aidera.",s:"Adage antique, repris par La Fontaine"},
{t:"Tout vainqueur insolent à sa perte travaille.",s:"La Fontaine"},
{t:"Rien ne sert de courir, il faut partir à point.",s:"La Fontaine"},
{t:"Patience et longueur de temps font plus que force ni que rage.",s:"La Fontaine"},
{t:"Ils peuvent parce qu'ils croient pouvoir.",s:"Virgile, Énéide"},
{t:"Tiens bon et garde-toi pour des jours meilleurs.",s:"Virgile, Énéide"},
{t:"Un jour, peut-être, il te sera doux de te souvenir même de ces épreuves.",s:"Virgile, Énéide"},
{t:"L'amour du pays vaincra.",s:"Virgile"},
{t:"Le travail opiniâtre vient à bout de tout.",s:"Virgile, Géorgiques"},
{t:"Ose savoir : aie le courage de te servir de ton propre entendement.",s:"Horace"},
{t:"Celui qui a commencé a fait la moitié de l'œuvre.",s:"Horace"},
{t:"Mêle un grain de folie à ta sagesse.",s:"Horace"},
{t:"La colère est une courte folie.",s:"Horace"},
{t:"C'est quand le voisin brûle qu'il s'agit de toi.",s:"Horace"},
{t:"Il est doux et beau de mourir pour la patrie.",s:"Horace"},
{t:"Le juste, ferme en son propos, ne tremble ni devant la foule ni devant le tyran.",s:"Horace"},
/* — Grèce antique — */
{t:"Viens les prendre.",s:"Léonidas aux Thermopyles, d'après Plutarque"},
{t:"Alors nous combattrons à l'ombre.",s:"Diénékès le Spartiate, d'après Hérodote"},
{t:"Reviens avec ton bouclier, ou dessus.",s:"Les mères spartiates, d'après Plutarque"},
{t:"En temps de paix, les fils enterrent leurs pères ; en temps de guerre, les pères enterrent leurs fils.",s:"Hérodote"},
{t:"Frappe, mais écoute.",s:"Thémistocle à Eurybiade, d'après Plutarque"},
{t:"Le secret du bonheur est la liberté ; le secret de la liberté, le courage.",s:"Périclès, d'après Thucydide"},
{t:"Les braves sont ceux qui voient clairement ce qui les attend, gloire comme danger, et qui pourtant y vont.",s:"Périclès, d'après Thucydide"},
{t:"Le fort fait ce qu'il peut, le faible subit ce qu'il doit.",s:"Thucydide"},
{t:"L'école la plus dure fait les meilleurs soldats.",s:"Thucydide"},
{t:"Le combat est le père de toutes choses.",s:"Héraclite"},
{t:"On ne se baigne jamais deux fois dans le même fleuve.",s:"Héraclite"},
{t:"Le caractère d'un homme est son destin.",s:"Héraclite"},
{t:"Deviens ce que tu es, quand tu l'auras appris.",s:"Pindare"},
{t:"La victoire sur soi est la plus grande des victoires.",s:"Platon"},
{t:"Le début est la moitié du tout.",s:"Platon"},
{t:"La première et la plus grande victoire, c'est de se conquérir soi-même.",s:"Platon"},
{t:"Nous sommes ce que nous faisons de manière répétée. L'excellence n'est donc pas un acte, mais une habitude.",s:"D'après Aristote"},
{t:"C'est en faisant qu'on apprend ce qu'il faut faire.",s:"Aristote"},
{t:"Le courage est la première des qualités humaines, car elle garantit toutes les autres.",s:"Aristote"},
{t:"Nous faisons la guerre pour vivre en paix.",s:"Aristote"},
{t:"À travers les épreuves, la connaissance.",s:"Eschyle"},
{t:"Il faut souffrir pour comprendre.",s:"Eschyle"},
{t:"Le succès engendre le succès.",s:"Sophocle"},
{t:"Le ciel n'aide jamais l'homme qui n'agit pas.",s:"Sophocle"},
{t:"La fortune ne se range pas du côté des cœurs abattus.",s:"Sophocle"},
{t:"Bien plus fort est celui qui se maîtrise que celui qui maîtrise les autres.",s:"D'après Démocrite"},
{t:"L'audace est le commencement de l'action, mais la fortune est maîtresse de l'issue.",s:"Démocrite"},
{t:"Rien n'existe hors des atomes et du vide : le reste n'est qu'opinion.",s:"Démocrite"},
{t:"Connais-toi toi-même.",s:"Inscription du temple de Delphes"},
{t:"Rien de trop.",s:"Inscription du temple de Delphes"},
{t:"Une vie sans examen ne vaut pas d'être vécue.",s:"Socrate, d'après Platon"},
{t:"Je ne suis ni Athénien, ni Grec : je suis citoyen du monde.",s:"Socrate, d'après Plutarque"},
{t:"Que celui qui veut mouvoir le monde commence par se mouvoir lui-même.",s:"Attribué à Socrate"},
{t:"Je cherche un homme.",s:"Diogène, lanterne à la main"},
{t:"Ôte-toi de mon soleil.",s:"Diogène à Alexandre le Grand"},
{t:"Il n'est rien d'impossible à celui qui essaie.",s:"Attribué à Alexandre le Grand"},
{t:"Je ne crains pas une armée de lions conduite par un mouton ; je crains une armée de moutons conduite par un lion.",s:"Attribué à Alexandre le Grand"},
{t:"Il n'y a rien de plus royal que le travail.",s:"Alexandre le Grand, d'après Plutarque"},
{t:"La discipline est l'âme d'une armée.",s:"Xénophon"},
{t:"La mer ! La mer !",s:"Les Dix Mille de Xénophon, apercevant le salut"},
{t:"Sois tel que tu voudrais paraître.",s:"Socrate, d'après Xénophon"},
{t:"La faim est le meilleur des assaisonnements.",s:"Xénophon"},
{t:"Sois lent à la délibération, prompt à l'exécution.",s:"Isocrate"},
{t:"La racine de l'éducation est amère, mais son fruit est doux.",s:"Attribué à Aristote, d'après Diogène Laërce"},
{t:"Les petites occasions font souvent les grandes entreprises.",s:"Démosthène"},
{t:"Les mots sans les actes sont vains.",s:"Démosthène"},
{t:"Rien de grand ne se fait sans audace.",s:"D'après Périclès"},
{t:"Le temps est le plus sage des conseillers.",s:"Périclès, d'après Plutarque"},
{t:"Ne remets pas au lendemain : la moisson n'attend pas.",s:"Hésiode"},
{t:"Devant la vertu, les dieux immortels ont placé la sueur.",s:"Hésiode"},
{t:"Ajoute peu à peu, et le peu deviendra beaucoup.",s:"Hésiode"},
{t:"Sois vaillant, et laisse faire aux dieux.",s:"Homère, Iliade"},
{t:"Toujours être le meilleur et surpasser les autres.",s:"Homère, Iliade"},
{t:"Il n'est pas honteux de fuir le malheur, même de nuit.",s:"Homère, Iliade"},
{t:"L'homme aux mille ruses ne resta jamais sans ressource.",s:"Homère, Odyssée"},
{t:"Endure, mon cœur : tu as connu pire.",s:"Homère, Odyssée"},
{t:"Un présage vaut mieux que tous : combattre pour sa patrie.",s:"Homère, Iliade"},
{t:"La jeunesse et la beauté passent ; la vertu demeure.",s:"D'après Ésope"},
{t:"Les actes prouvent l'homme.",s:"Ésope"},
{t:"L'union fait la force.",s:"Ésope, Le vieillard et ses fils"},
{t:"Petit à petit fait beaucoup.",s:"Ésope"},
{t:"Ce sont les tonneaux vides qui font le plus de bruit.",s:"Proverbe grec"},
{t:"La société prospère quand les vieillards plantent des arbres à l'ombre desquels ils ne s'assiéront jamais.",s:"Proverbe grec"},
{t:"Commencer, c'est la moitié de l'action.",s:"Proverbe grec"},
{t:"Le sage porte tout ce qu'il possède avec lui.",s:"Bias de Priène"},
{t:"Saisis l'occasion.",s:"Pittacos de Mytilène"},
{t:"La mesure est la meilleure des choses.",s:"Cléobule de Lindos"},
/* — Sparte — */
{t:"Si.",s:"Réponse des Spartiates à Philippe II menaçant d'entrer en Laconie"},
{t:"Les murs de Sparte, ce sont ses jeunes gens ; ses frontières, la pointe de leurs lances.",s:"Agésilas, roi de Sparte"},
{t:"Nous ne demandons pas combien sont les ennemis, mais où ils sont.",s:"Agis, roi de Sparte, d'après Plutarque"},
{t:"Mange bien, car demain nous dînerons chez Hadès.",s:"Léonidas avant les Thermopyles, d'après Plutarque"},
{t:"Passant, va dire à Sparte que nous gisons ici, fidèles à ses lois.",s:"Épitaphe des Thermopyles, Simonide"},
{t:"À Sparte, ce n'est pas la richesse qui honore, mais la vaillance.",s:"D'après Plutarque"},
{t:"L'épée courte suffit : il n'y a qu'un pas de plus à faire vers l'ennemi.",s:"Apophtegme spartiate"},
/* — Stoïciens — */
{t:"Ce n'est pas parce que les choses sont difficiles que nous n'osons pas ; c'est parce que nous n'osons pas qu'elles sont difficiles.",s:"Sénèque"},
{t:"La vie, ce n'est pas d'attendre que l'orage passe, c'est d'apprendre à naviguer sous la pluie.",s:"D'après Sénèque"},
{t:"Il n'est point de vent favorable pour qui ne sait où il va.",s:"Sénèque"},
{t:"Le feu éprouve l'or, le malheur éprouve les braves.",s:"Sénèque"},
{t:"Un athlète ne peut apporter une grande ardeur au combat s'il n'a jamais reçu de coups.",s:"Sénèque"},
{t:"La vie est un combat.",s:"Sénèque (Vivere militare est)"},
{t:"Hâte-toi de bien vivre, et songe que chaque jour est à lui seul une vie.",s:"Sénèque"},
{t:"Nous souffrons plus souvent en imagination qu'en réalité.",s:"Sénèque"},
{t:"La difficulté vient de notre manque de confiance.",s:"Sénèque"},
{t:"Tant que tu vis, apprends à vivre.",s:"Sénèque"},
{t:"C'est pendant l'orage qu'on connaît le pilote.",s:"Sénèque"},
{t:"Le destin conduit celui qui consent, et traîne celui qui résiste.",s:"Sénèque, d'après Cléanthe"},
{t:"Personne ne peut avoir tout ce qu'il veut, mais il peut ne pas vouloir ce qu'il n'a pas.",s:"Sénèque"},
{t:"L'homme le plus puissant est celui qui est maître de lui-même.",s:"Sénèque"},
{t:"Ce qui a été dur à supporter est doux à rappeler.",s:"Sénèque"},
{t:"Tu as pouvoir sur ton esprit, pas sur les événements. Comprends-le, et tu trouveras la force.",s:"Marc Aurèle"},
{t:"L'obstacle est matière à action. Ce qui barre la route fait faire du chemin.",s:"Marc Aurèle"},
{t:"Que la force me soit donnée de supporter ce qui ne peut être changé.",s:"Marc Aurèle"},
{t:"Ne discute plus de ce que doit être l'homme de bien : sois-le.",s:"Marc Aurèle"},
{t:"La meilleure vengeance, c'est de ne pas ressembler à ton ennemi.",s:"Marc Aurèle"},
{t:"Au matin, quand tu as peine à te lever, dis-toi : je m'éveille pour faire œuvre d'homme.",s:"Marc Aurèle"},
{t:"Regarde en toi : c'est là qu'est la source du bien, toujours prête à jaillir si tu creuses toujours.",s:"Marc Aurèle"},
{t:"Ce qui n'est pas utile à la ruche n'est pas utile à l'abeille.",s:"Marc Aurèle"},
{t:"La vie de l'homme est ce qu'en font ses pensées.",s:"Marc Aurèle"},
{t:"Fais chaque action de ta vie comme si c'était la dernière.",s:"Marc Aurèle"},
{t:"L'art de vivre ressemble plus à la lutte qu'à la danse.",s:"Marc Aurèle"},
{t:"Il faut se tenir droit, non pas être tenu droit.",s:"Marc Aurèle"},
{t:"Ce qui dépend de nous : nos jugements, nos désirs, nos actions. Le reste ne nous appartient pas.",s:"Épictète"},
{t:"Ce ne sont pas les choses qui troublent les hommes, mais les jugements qu'ils portent sur elles.",s:"Épictète"},
{t:"Aucun grand talent ne vient sans effort : veux-tu vaincre aux Jeux ? Il faut t'exercer, suer, souffrir.",s:"Épictète"},
{t:"Supporte et abstiens-toi.",s:"Épictète"},
{t:"Tu veux être vainqueur olympique ? Moi aussi. Mais examine d'abord ce qui précède et ce qui suit.",s:"Épictète"},
{t:"C'est le propre de l'ignorant d'accuser les autres ; l'homme instruit s'accuse lui-même ; le sage n'accuse personne.",s:"Épictète"},
{t:"La difficulté montre ce que sont les hommes.",s:"Épictète"},
{t:"Ne dis pas des choses : je les ai perdues. Dis : je les ai rendues.",s:"Épictète"},
/* — Rome, généraux et historiens — */
{t:"J'aime la trahison, mais je hais les traîtres.",s:"Attribué à Jules César, d'après Plutarque"},
{t:"Mieux vaut être le premier dans son village que le second à Rome.",s:"Jules César, d'après Plutarque"},
{t:"Dans les grandes entreprises, il faut donner sa chance au hasard.",s:"D'après Jules César"},
{t:"Les hommes croient volontiers ce qu'ils désirent.",s:"Jules César"},
{t:"Nous trouverons un chemin, ou nous en créerons un.",s:"Attribué à Hannibal"},
{t:"Prépare la guerre, puisque tu n'as pas su supporter la paix.",s:"Scipion l'Africain à Hannibal, avant Zama"},
{t:"Rome ne paie pas ses ennemis, elle les vainc.",s:"D'après l'adage romain"},
{t:"Il faut détruire Carthage.",s:"Caton l'Ancien"},
{t:"Fais et endure : c'est le propre du Romain.",s:"D'après Tite-Live (Mucius Scaevola)"},
{t:"La fortune aide les audacieux.",s:"Tite-Live"},
{t:"Mieux vaut tard que jamais.",s:"Tite-Live"},
{t:"Toute chose a été plus faible à ses débuts.",s:"Tite-Live"},
{t:"Chacun est l'artisan de sa propre fortune.",s:"Salluste, d'après Appius Claudius"},
{t:"La concorde fait grandir les petites choses, la discorde ruine les plus grandes.",s:"Salluste"},
{t:"Avant d'agir, réfléchis ; quand tu as réfléchi, agis vite.",s:"Salluste"},
{t:"Les qualités propres d'un général sont le jugement et la prudence.",s:"Tacite"},
{t:"Ils font un désert et appellent cela la paix.",s:"Calgacos, d'après Tacite"},
{t:"Le désir de la gloire est la dernière chose dont se défont les sages.",s:"Tacite"},
{t:"La valeur des soldats vaut ce que vaut leur chef.",s:"D'après Végèce"},
{t:"Peu d'hommes naissent braves ; beaucoup le deviennent par le travail et la discipline.",s:"Végèce"},
{t:"Une armée s'entraîne en paix pour vaincre en guerre.",s:"D'après Végèce"},
{t:"Qui aspire à la victoire doit instruire ses soldats avec rigueur.",s:"Végèce"},
{t:"L'audace vaut un rempart.",s:"Salluste"},
{t:"L'empire appartient aux plus dignes.",s:"D'après Tacite"},
{t:"La modération est la plus sûre des forteresses.",s:"D'après Marc Aurèle"},
{t:"Ce que tu fais, fais-le vite et bien.",s:"D'après Caton l'Ancien"},
{t:"Rien n'est difficile aux braves.",s:"D'après Cicéron"},
{t:"La gloire suit la vertu comme son ombre.",s:"Cicéron"},
{t:"Plus grande est la difficulté, plus grande est la gloire.",s:"Cicéron"},
{t:"L'homme est son pire ennemi.",s:"Cicéron"},
{t:"Toute la vie d'un philosophe est une préparation à la mort.",s:"Cicéron"},
{t:"Que les armes cèdent à la toge.",s:"Cicéron"},
/* — Sun Tzu et pensée chinoise — */
{t:"L'art suprême de la guerre est de soumettre l'ennemi sans combattre.",s:"Sun Tzu, L'Art de la guerre"},
{t:"Connais ton ennemi et connais-toi toi-même : en cent batailles, tu ne seras jamais en péril.",s:"Sun Tzu, L'Art de la guerre"},
{t:"Toute guerre est fondée sur la tromperie.",s:"Sun Tzu, L'Art de la guerre"},
{t:"La victoire appartient à celui qui sait quand combattre et quand ne pas combattre.",s:"Sun Tzu, L'Art de la guerre"},
{t:"Au milieu du chaos réside aussi l'opportunité.",s:"D'après Sun Tzu"},
{t:"Qui excelle à vaincre triomphe avant que la bataille ne commence.",s:"Sun Tzu, L'Art de la guerre"},
{t:"La rapidité est l'essence même de la guerre.",s:"Sun Tzu, L'Art de la guerre"},
{t:"Sois subtil jusqu'à l'invisible ; sois mystérieux jusqu'à l'inaudible : alors tu tiendras le sort de l'ennemi.",s:"Sun Tzu, L'Art de la guerre"},
{t:"L'eau n'a pas de forme constante ; la guerre n'a pas de conditions constantes.",s:"Sun Tzu, L'Art de la guerre"},
{t:"Le général victorieux fait beaucoup de calculs avant la bataille.",s:"Sun Tzu, L'Art de la guerre"},
{t:"Qui connaît l'autre et se connaît, en cent combats ne sera point défait.",s:"Sun Tzu, L'Art de la guerre"},
{t:"L'invincibilité se trouve dans la défense ; la possibilité de victoire, dans l'attaque.",s:"Sun Tzu, L'Art de la guerre"},
{t:"Un voyage de mille lieues commence par un premier pas.",s:"Lao Tseu"},
{t:"Celui qui vainc les autres est fort ; celui qui se vainc lui-même est puissant.",s:"Lao Tseu"},
{t:"Celui qui sait se contenter est riche.",s:"Lao Tseu"},
{t:"Les grandes réalisations sont faites d'une somme de petites choses.",s:"Lao Tseu"},
{t:"L'eau qui est souple vient à bout du roc qui est dur.",s:"D'après Lao Tseu"},
{t:"L'arbre qui remplit tes bras est né d'un germe infime.",s:"Lao Tseu"},
{t:"Notre plus grande gloire n'est pas de ne jamais tomber, mais de nous relever à chaque chute.",s:"Confucius"},
{t:"Peu importe la lenteur à laquelle tu avances, tant que tu ne t'arrêtes pas.",s:"D'après Confucius"},
{t:"L'homme supérieur est exigeant envers lui-même ; l'homme vulgaire est exigeant envers les autres.",s:"Confucius"},
{t:"Quand tu vois un homme de valeur, cherche à l'égaler ; quand tu vois un homme sans valeur, examine-toi.",s:"Confucius"},
{t:"Celui qui déplace une montagne commence par déplacer de petites pierres.",s:"Confucius"},
{t:"L'expérience est une lanterne accrochée dans le dos : elle n'éclaire que le chemin parcouru.",s:"Proverbe chinois"},
{t:"Le meilleur moment pour planter un arbre était il y a vingt ans. Le deuxième meilleur moment, c'est maintenant.",s:"Proverbe chinois"},
{t:"La perle ne se polit pas sans frottement, ni l'homme sans épreuves.",s:"Proverbe chinois"},
{t:"Mieux vaut allumer une bougie que maudire l'obscurité.",s:"Proverbe chinois"},
{t:"Qui veut gravir une montagne commence par le bas.",s:"Proverbe chinois"},
{t:"Un peu d'impatience ruine un grand projet.",s:"Proverbe chinois"},
{t:"Creuse ton puits avant d'avoir soif.",s:"Proverbe chinois"},
{t:"Le général qui gagne fait retraite quand il le faut.",s:"D'après les Trente-Six Stratagèmes"},
{t:"Traverse la mer à l'insu du ciel.",s:"Les Trente-Six Stratagèmes"},
{t:"Attends en te reposant que l'ennemi s'épuise.",s:"Les Trente-Six Stratagèmes"},
/* — Japon — */
{t:"Tombe sept fois, relève-toi huit.",s:"Proverbe japonais"},
{t:"Ne crains pas d'avancer lentement, crains seulement de t'arrêter.",s:"Proverbe japonais"},
{t:"La défaite s'apprend dans la victoire, la victoire dans la défaite.",s:"Proverbe japonais"},
{t:"Même un chemin de mille lieues se parcourt pas à pas.",s:"Proverbe japonais"},
{t:"Le sabre est l'âme du samouraï.",s:"Adage japonais"},
{t:"Aujourd'hui, victoire sur celui que tu étais hier ; demain, victoire sur de moindres que toi.",s:"Miyamoto Musashi"},
{t:"Ne fais rien qui ne soit d'aucune utilité.",s:"Miyamoto Musashi, Traité des cinq roues"},
{t:"Connais les voies de toutes les professions.",s:"Miyamoto Musashi, Traité des cinq roues"},
{t:"En stratégie, il est important de voir ce qui est loin comme proche, et ce qui est proche comme lointain.",s:"Miyamoto Musashi, Traité des cinq roues"},
{t:"Mille jours d'entraînement pour forger, dix mille jours pour polir.",s:"Miyamoto Musashi, Traité des cinq roues"},
{t:"Pense légèrement de toi-même et profondément du monde.",s:"Miyamoto Musashi, Dokkōdō"},
{t:"Ne regrette jamais ce que tu as fait.",s:"Miyamoto Musashi, Dokkōdō"},
{t:"Tu peux abandonner ton corps, mais garde ton honneur.",s:"Miyamoto Musashi, Dokkōdō"},
{t:"La Voie du samouraï se trouve dans la mort.",s:"Yamamoto Tsunetomo, Hagakure"},
{t:"Il y a quelque chose à apprendre d'une averse : se résoudre à être trempé dès le début.",s:"Yamamoto Tsunetomo, Hagakure"},
{t:"Les affaires importantes doivent être traitées avec légèreté ; les petites, avec sérieux.",s:"Yamamoto Tsunetomo, Hagakure"},
{t:"Sept respirations suffisent pour prendre une décision.",s:"Yamamoto Tsunetomo, Hagakure"},
{t:"Le guerrier accompli n'est ni belliqueux ni coléreux.",s:"D'après le Bushidō"},
{t:"Fleur de cerisier parmi les fleurs, guerrier parmi les hommes.",s:"Proverbe japonais"},
{t:"Après la pluie, la terre se durcit.",s:"Proverbe japonais"},
{t:"Le bambou plie sous la neige, mais ne rompt pas.",s:"Proverbe japonais"},
{t:"La vision sans l'action est un rêve éveillé ; l'action sans vision, un cauchemar.",s:"Proverbe japonais"},
{t:"Le clou qui dépasse appelle le marteau.",s:"Proverbe japonais"},
/* — Vikings et Hávamál — */
{t:"Le bétail meurt, les parents meurent ; mais la réputation de celui qui s'est bien conduit ne meurt jamais.",s:"Hávamál, poème viking"},
{t:"Mieux vaut vivre que gésir sans vie : l'homme vivant obtient toujours la vache.",s:"Hávamál, poème viking"},
{t:"L'homme sans peur traverse la vie ; le lâche croit que tout est piège.",s:"D'après le Hávamál"},
{t:"Debout tôt doit être celui qui veut prendre le bien ou la vie d'un autre : le loup couché n'a pas de gigot.",s:"Hávamál, poème viking"},
{t:"Ne quitte pas tes armes d'un pas sur le chemin : on ne sait jamais quand la lance sera nécessaire.",s:"Hávamál, poème viking"},
{t:"Le feu est la meilleure chose pour les fils des hommes, et la vue du soleil.",s:"Hávamál, poème viking"},
{t:"Les rois périssent, les dieux s'éteignent : seule demeure la gloire des hauts faits.",s:"D'après la poésie scandinave"},
{t:"Là où tu reconnais le mal, appelle-le mal, et ne donne pas de trêve à tes ennemis.",s:"Hávamál, poème viking"},
/* — Proverbes du monde — */
{t:"Si tu veux aller vite, marche seul ; si tu veux aller loin, marchons ensemble.",s:"Proverbe africain"},
{t:"Chaque matin, en Afrique, une gazelle se réveille et sait qu'elle doit courir plus vite que le lion, ou mourir.",s:"Proverbe africain"},
{t:"La chute n'est pas un échec ; l'échec, c'est de rester là où l'on est tombé.",s:"Proverbe africain"},
{t:"C'est au bout de la vieille corde qu'on tisse la nouvelle.",s:"Proverbe africain"},
{t:"Les chiens aboient, la caravane passe.",s:"Proverbe arabe"},
{t:"Attache d'abord ton chameau, puis remets-t'en à Dieu.",s:"Proverbe arabe"},
{t:"La patience est la clé du bien-être.",s:"Proverbe arabe"},
{t:"Ce qui ne te tue pas te rend plus fort.",s:"Nietzsche, Crépuscule des idoles"},
{t:"Il faut porter du chaos en soi pour accoucher d'une étoile qui danse.",s:"Nietzsche, Ainsi parlait Zarathoustra"},
{t:"Deviens ce que tu es.",s:"Nietzsche, d'après Pindare"},
{t:"Celui qui a un pourquoi qui lui tient lieu de but peut vivre avec n'importe quel comment.",s:"Nietzsche"},
{t:"L'homme qui déplace une montagne commence par les petites pierres.",s:"Proverbe oriental"},
{t:"Qui n'avance pas recule.",s:"Proverbe d'origine médiévale"},
{t:"La forge fait le forgeron, le combat fait le guerrier.",s:"Proverbe médiéval"},
{t:"Pierre qui roule n'amasse pas mousse.",s:"Proverbe, d'après Publilius Syrus"},
{t:"Qui ne risque rien n'a rien.",s:"Proverbe français"},
{t:"À cœur vaillant rien d'impossible.",s:"Devise de Jacques Cœur"},
{t:"Fais ce que dois, advienne que pourra.",s:"Devise de chevalerie"},
{t:"Sans peur et sans reproche.",s:"Devise du chevalier Bayard"},
{t:"Plutôt mourir que trahir.",s:"Devise de chevalerie"},
{t:"Un pour tous, tous pour un.",s:"Devise, popularisée par Alexandre Dumas"},
/* — Moyen Âge, Renaissance — */
{t:"Les hommes d'armes batailleront, et Dieu donnera la victoire.",s:"Jeanne d'Arc"},
{t:"Je ne crains rien, car Dieu est avec moi.",s:"D'après Jeanne d'Arc"},
{t:"Il vaut mieux être craint qu'aimé, si l'on ne peut être les deux.",s:"Machiavel, Le Prince"},
{t:"Il n'y a pas d'entreprise plus difficile que d'introduire un ordre nouveau.",s:"Machiavel, Le Prince"},
{t:"La fortune est femme : elle cède plus volontiers aux audacieux.",s:"Machiavel, Le Prince"},
{t:"Les guerres commencent quand on veut, mais ne finissent pas quand on le souhaite.",s:"Machiavel"},
{t:"Qui veut être obéi doit savoir commander.",s:"Machiavel"},
{t:"L'impatience est la marque des faibles ; la constance, celle des forts.",s:"D'après Machiavel"},
{t:"La vraie victoire est celle que l'on remporte sur soi-même.",s:"D'après Érasme"},
{t:"Il n'est de richesse que d'hommes.",s:"Jean Bodin"},
{t:"Science sans conscience n'est que ruine de l'âme.",s:"Rabelais"},
{t:"La persévérance vient à bout de tout.",s:"Proverbe de la Renaissance"},
/* — Grand Siècle et Lumières — */
{t:"À vaincre sans péril, on triomphe sans gloire.",s:"Corneille, Le Cid"},
{t:"Aux âmes bien nées, la valeur n'attend point le nombre des années.",s:"Corneille, Le Cid"},
{t:"Nous partîmes cinq cents ; mais par un prompt renfort, nous nous vîmes trois mille en arrivant au port.",s:"Corneille, Le Cid"},
{t:"Plus l'offenseur est cher, et plus grande est l'offense.",s:"Corneille, Le Cid"},
{t:"Le combat cessa faute de combattants.",s:"Corneille, Le Cid"},
{t:"Cent fois sur le métier remettez votre ouvrage.",s:"Boileau"},
{t:"Hâtez-vous lentement, et sans perdre courage.",s:"Boileau"},
{t:"Nous n'avons pas assez de force pour suivre toute notre raison.",s:"La Rochefoucauld"},
{t:"La parfaite valeur est de faire sans témoins ce qu'on serait capable de faire devant tout le monde.",s:"La Rochefoucauld"},
{t:"Il n'y a point de héros pour son valet de chambre.",s:"Attribué à Mme Cornuel"},
{t:"Le vrai moyen d'être trompé, c'est de se croire plus fin que les autres.",s:"La Rochefoucauld"},
{t:"On ne trouve jamais mieux la force que dans la nécessité.",s:"D'après Vauban"},
{t:"Place assiégée par Vauban, place prise ; place défendue par Vauban, place imprenable.",s:"Adage militaire du Grand Siècle"},
{t:"L'audace, encore de l'audace, toujours de l'audace, et la Patrie sera sauvée !",s:"Danton, 1792"},
{t:"La discipline fait la force principale des armées.",s:"Règlement militaire français, XIXe siècle"},
{t:"Il faut cultiver notre jardin.",s:"Voltaire, Candide"},
{t:"Le mieux est l'ennemi du bien.",s:"Voltaire"},
{t:"J'ai décidé d'être heureux parce que c'est bon pour la santé.",s:"Voltaire"},
{t:"L'homme est né libre, et partout il est dans les fers.",s:"Rousseau"},
{t:"La patience est amère, mais son fruit est doux.",s:"Rousseau"},
/* — Napoléon et chefs de guerre modernes — */
{t:"Impossible n'est pas français.",s:"Napoléon, lettre de 1813"},
{t:"La victoire appartient au plus opiniâtre.",s:"Attribué à Napoléon"},
{t:"Du sublime au ridicule, il n'y a qu'un pas.",s:"Napoléon"},
{t:"Soldats, songez que du haut de ces pyramides, quarante siècles vous contemplent.",s:"Napoléon, campagne d'Égypte"},
{t:"Le courage de deux heures du matin est le plus rare : celui de l'improviste.",s:"Napoléon, d'après Las Cases"},
{t:"En guerre comme en amour, pour en finir, il faut se voir de près.",s:"Napoléon"},
{t:"La mort n'est rien ; mais vivre vaincu et sans gloire, c'est mourir tous les jours.",s:"Napoléon"},
{t:"Tout soldat français porte dans sa giberne le bâton de maréchal de France.",s:"Attribué à Napoléon"},
{t:"C'est avec des hochets qu'on mène les hommes.",s:"Napoléon"},
{t:"L'art le plus difficile n'est pas de choisir les hommes, mais de donner aux hommes qu'on a choisis toute la valeur qu'ils peuvent avoir.",s:"Napoléon"},
{t:"Il ne faut jamais interrompre un ennemi qui est en train de faire une erreur.",s:"Attribué à Napoléon"},
{t:"La meilleure façon de tenir sa parole est de ne jamais la donner.",s:"Napoléon"},
{t:"Une armée marche sur son estomac.",s:"Attribué à Napoléon"},
{t:"Qui sait tout souffrir peut tout oser.",s:"Vauvenargues"},
{t:"Pour exécuter de grandes choses, il faut vivre comme si on ne devait jamais mourir.",s:"Vauvenargues"},
{t:"Le corps a ses grâces, l'esprit ses talents ; le cœur seul a des vertus.",s:"Vauvenargues"},
{t:"La guerre est la continuation de la politique par d'autres moyens.",s:"Clausewitz, De la guerre"},
{t:"Tout est très simple à la guerre, mais la chose la plus simple est difficile.",s:"Clausewitz, De la guerre"},
{t:"Le meilleur plan ne survit pas au premier contact avec l'ennemi.",s:"D'après Moltke l'Ancien"},
{t:"La stratégie est un système d'expédients.",s:"Moltke l'Ancien"},
{t:"La balle est folle, la baïonnette est sage.",s:"Souvorov, maréchal russe"},
{t:"Entraînement difficile, guerre facile.",s:"Souvorov, maréchal russe"},
{t:"La rapidité et la surprise remplacent le nombre.",s:"D'après Souvorov"},
{t:"Un chef est un marchand d'espérance.",s:"Attribué à Napoléon"},
{t:"L'audace est le secret des plus belles réussites.",s:"D'après Frédéric II de Prusse"},
{t:"Il n'est pas nécessaire d'espérer pour entreprendre, ni de réussir pour persévérer.",s:"Devise attribuée à Guillaume d'Orange"},
{t:"Défendre tout, c'est ne rien défendre.",s:"Frédéric II de Prusse"},
{t:"Les batailles se gagnent avec les jambes des soldats.",s:"Maxime militaire, d'après Saxe et Souvorov"},
{t:"Rien n'est perdu tant que le courage demeure.",s:"Maxime militaire ancienne"},
{t:"On ne s'appuie que sur ce qui résiste.",s:"Attribué à Andrieux, repris par les militaires"},
{t:"La garde meurt mais ne se rend pas.",s:"Attribué à Cambronne, Waterloo"},
{t:"De l'audace, du calcul, et pas d'hésitation.",s:"D'après les maximes de guerre de Napoléon"},
{t:"Qui embrasse trop mal étreint.",s:"Proverbe, appliqué à la guerre par Frédéric II"},
{t:"Rien qu'une bataille perdue peut être à moitié aussi triste qu'une bataille gagnée.",s:"Wellington, après Waterloo"},
{t:"Le champ de bataille est un lieu de constante erreur : gagne celui qui en commet le moins.",s:"D'après les maximes militaires du XIXe siècle"},
/* — XIXe siècle — */
{t:"Ceux qui vivent, ce sont ceux qui luttent.",s:"Victor Hugo"},
{t:"L'avenir est une porte, le passé en est la clé.",s:"Victor Hugo"},
{t:"La persévérance est le secret de tous les triomphes.",s:"Victor Hugo"},
{t:"Rien n'est plus puissant qu'une idée dont l'heure est venue.",s:"D'après Victor Hugo"},
{t:"Le génie est fait d'un pour cent d'inspiration et de quatre-vingt-dix-neuf pour cent de transpiration.",s:"Edison"},
{t:"Je n'ai pas échoué : j'ai trouvé dix mille moyens qui ne fonctionnent pas.",s:"Attribué à Edison"},
{t:"Le bonheur est une habitude à cultiver.",s:"D'après les moralistes du XIXe siècle"},
{t:"La chance ne sourit qu'aux esprits bien préparés.",s:"Pasteur"},
{t:"Dans les champs de l'observation, le hasard ne favorise que les esprits préparés.",s:"Pasteur"},
{t:"Travaille comme si tu devais vivre cent ans, prie comme si tu devais mourir demain.",s:"Attribué à Benjamin Franklin"},
{t:"L'énergie et la persistance viennent à bout de tout.",s:"Benjamin Franklin"},
{t:"Il y a bien des manières de ne pas réussir, mais la plus sûre est de ne jamais prendre de risques.",s:"Benjamin Franklin"},
{t:"Ne remets pas à demain ce que tu peux faire aujourd'hui.",s:"Benjamin Franklin, d'après l'adage"},
{t:"Celui qui déplace la montagne, c'est celui qui commence à enlever les pierres.",s:"Proverbe repris par les moralistes"},
{t:"Notre patience obtiendra plus que notre force.",s:"Edmund Burke"},
{t:"Nous améliorons nous-mêmes par des victoires sur nous-mêmes. Il doit y avoir des combats, et il faut les gagner.",s:"Edward Gibbon"},
{t:"La discipline est la mère du succès.",s:"D'après Eschyle"},
{t:"Le fer se forge par le fer, l'homme par l'homme.",s:"Livre des Proverbes"},
{t:"L'Éternel est un homme de guerre.",s:"Livre de l'Exode"},
{t:"Malheur à l'homme seul : s'il tombe, nul ne le relève.",s:"L'Ecclésiaste"},
{t:"Il y a un temps pour la guerre et un temps pour la paix.",s:"L'Ecclésiaste"},
{t:"La course n'est point aux agiles, ni la guerre aux vaillants : tout dépend du temps et des circonstances.",s:"L'Ecclésiaste"},
{t:"Comme le visage se reflète dans l'eau, le cœur de l'homme se reflète dans l'homme.",s:"Livre des Proverbes"},
{t:"Mieux vaut la fin d'une chose que son commencement ; mieux vaut la patience que l'orgueil.",s:"L'Ecclésiaste"},
/* — Complément : maximes et apophtegmes — */
{t:"La récompense d'une chose bien faite, c'est de l'avoir faite.",s:"Sénèque"},
{t:"Il faut toute la vie pour apprendre à vivre.",s:"Sénèque"},
{t:"Ce n'est pas que nous disposons de peu de temps, c'est que nous en perdons beaucoup.",s:"Sénèque, De la brièveté de la vie"},
{t:"Les plus grands empires se sont bâtis pas à pas.",s:"D'après Sénèque"},
{t:"Ose : la fortune favorise les audacieux.",s:"Adage latin (Audentes fortuna juvat)"},
{t:"L'habitude est une seconde nature.",s:"Adage latin, d'après Aristote"},
{t:"La répétition est la mère des études.",s:"Adage latin (Repetitio mater studiorum)"},
{t:"Le travail vainc tout.",s:"Virgile (Labor omnia vincit)"},
{t:"Plus d'honneur dans la difficulté.",s:"Adage latin"},
{t:"L'exception confirme la règle.",s:"Adage de droit romain"},
{t:"Une main lave l'autre.",s:"Adage latin, d'après Épicharme"},
{t:"Qui se ressemble s'assemble.",s:"Adage antique"},
{t:"Loin des yeux, loin du cœur.",s:"Adage antique"},
{t:"Le silence vaut un aveu.",s:"Adage de droit romain"},
{t:"Souviens-toi de te méfier.",s:"Devise antique, d'après Épicharme"},
{t:"Chaque homme forge son destin.",s:"D'après Salluste"},
{t:"L'envie est l'ombre de la gloire.",s:"D'après les moralistes latins"},
{t:"L'ennemi le plus dangereux est celui qu'on méprise.",s:"D'après Tite-Live"},
{t:"C'est quand l'ennemi paraît vaincu qu'il est le plus à craindre.",s:"D'après Végèce"},
{t:"Ne méprise jamais un ennemi, si petit soit-il.",s:"Maxime militaire antique"},
{t:"Qui craint de souffrir souffre déjà de ce qu'il craint.",s:"Montaigne"},
{t:"La valeur a sa limite comme les autres vertus : franchie, elle devient vice.",s:"Montaigne"},
{t:"Il faut avoir l'âme d'un lutteur et le corps d'un athlète.",s:"D'après Montaigne"},
{t:"Le monde est un branloire pérenne : la constance même n'est qu'un branle plus languissant.",s:"Montaigne"},
{t:"Savoir se contenter de peu est une grande richesse.",s:"D'après Épicure"},
{t:"Il n'est jamais trop tôt ni trop tard pour prendre soin de son âme.",s:"Épicure"},
{t:"La mort n'est rien pour nous : quand nous sommes, elle n'est pas ; quand elle est, nous ne sommes plus.",s:"Épicure"},
{t:"Le plus grand fruit de l'autosuffisance est la liberté.",s:"Épicure"},
{t:"Il faut rire et philosopher en même temps.",s:"Épicure"},
{t:"La nature humaine se révèle dans l'épreuve.",s:"D'après Plutarque"},
{t:"Le courage consiste à dominer sa peur, non à ne pas la ressentir.",s:"D'après Plutarque"},
{t:"L'esprit n'est pas un vase à remplir, mais un feu à allumer.",s:"Plutarque"},
{t:"Rome n'a pas été bâtie en un jour.",s:"Proverbe médiéval"},
{t:"Qui trop se hâte reste en chemin.",s:"Proverbe médiéval"},
{t:"Après l'effort, le réconfort.",s:"Proverbe français"},
{t:"Petit à petit, l'oiseau fait son nid.",s:"Proverbe français"},
{t:"Vingt fois sur le métier remettez votre ouvrage : polissez-le sans cesse et le repolissez.",s:"Boileau, L'Art poétique"},
{t:"Ce que l'on conçoit bien s'énonce clairement.",s:"Boileau"},
{t:"On a souvent besoin d'un plus petit que soi.",s:"La Fontaine"},
{t:"En toute chose il faut considérer la fin.",s:"La Fontaine"},
{t:"Il se faut entraider : c'est la loi de nature.",s:"La Fontaine"},
{t:"Travaillez, prenez de la peine : c'est le fonds qui manque le moins.",s:"La Fontaine, Le Laboureur et ses enfants"},
{t:"La méfiance est mère de la sûreté.",s:"La Fontaine"},
{t:"Selon que vous serez puissant ou misérable, les jugements de cour vous rendront blanc ou noir.",s:"La Fontaine"},
{t:"Plutôt souffrir que mourir, c'est la devise des hommes.",s:"La Fontaine"}
];
